### PR TITLE
improve vibe.d support!

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by 9il** [comment]
The idea is:
1. Use `version(Have_vibe_d)` to estimate if vibe.d is used.
2. Use `mixin` to generate proper code.
3. Use separate worker thread for rdkafka.
4. Send delegate to the worker thread to execute them.
5. Use vibed Tasks, Mutexes, and Conditions.

**Comment by yannick** [comment]
approach looks great. 
please add two examples, one for producer and one for consumer including 
loading of a config file that has metadata call enabled.

**Comment by 9il** [comment]
> please add two examples, one for producer and one for consumer including
> loading of a config file that has metadata call enabled.

OK

**Comment by yannick** [comment]
in the example please show how to use the kafka timestamp feature

**Comment by 9il** [comment]
A combination of https://github.com/dlang/dub/issues/904 and other bug which runs dub in infinity loop (100% CPU load). Because that I have changed the `dub.json` files. No to add vibe.d support project must be compiled with `--combined` flag

**Comment by 9il** [comment]
Configuration files are presented for `producer_vibed` and `consumer_vibed`.

**Comment by 9il** [comment]
Consumer has example with timestamps. Producer has not timestamp support because #7. Should I fix #7 ?

**Pull request merged**
